### ISSUE TITLE
Config variable for API key is incorrect

### ISSUE THREAD

**Issue by cafreeman** [smythey21/google-geocoding-api-elixir#1]
Hey there!

Thanks for making this library. It works great, but the README has a slight error.

The bottom of the README gives the following instructions for configuring your api key:

```elixir
config :google_geocoding_api,
  key: "YOUR_API_KEY"
```

This wasn't working for me, so I checked the source and found [this](https://github.com/smythey21/google-geocoding-api-elixir/blob/master/lib/google_geocoding_api.ex#L85)

Looks like the README ought to say:
```elixir
config :google_geocoding_api,
  api_key: "YOUR_API_KEY"
```

e.g. `key` => `api_key`

This certainly fixed things for me :)

**Comment by smythey21** [comment]
Thanks for pointing that out @cafreeman! I've updated the readme 🍻
